In [7]:
import pandas as pd

In [18]:
df= pd.read_csv("data/propublica_trump_spending-1.csv")
df

,type,source,date,amount,purpose_scrubbed,property_scrubbed,purpose,property,city,state
0,FEC,"Donald J. Trump for President, Inc.","Apr 30, 2015",1380.54,Lodging,Trump Hotel NY,TTW - TRAVEL: LODGING,TRUMP INTERNATIONAL HOTEL AND TOWER,New York,NY
1,FEC,"Donald J. Trump for President, Inc.","May 5, 2015",9583.33,Rent,Trump Tower Commercial LLC,TTW - RENT,TRUMP TOWER COMMERCIAL LLC,Hicksville,NY
2,FEC,"Donald J. Trump for President, Inc.","Jun 16, 2015",37993.04,Event,The Trump Corporation,"TTW - ONE-TIME REIMBURSEMENT FOR FACILITY, RE...",THE TRUMP CORPORATION,New York,NY
3,FEC,"Donald J. Trump for President, Inc.","Jun 16, 2015",3240.96,Lodging,Trump Soho NY,TTW - TRAVEL: LODGING,TRUMP SOHO,New York,NY
4,FEC,"Donald J. Trump for President, Inc.","Jun 16, 2015",9583.33,Rent,Trump Tower Commercial LLC,TTW - RENT,TRUMP TOWER COMMERCIAL LLC,Hicksville,NY
...,...,...,...,...,...,...,...,...,...,...
1188,government,Department of State,undefined,5583.13,Other,Trump Golf Resort Scotland,NaN,Trump Turnberry,Turnberry,Scotland
1189,government,Department of State,undefined,4853.29,Other,Trump Hotel Vancouver,NaN,Trump International Hotel & Tower Vancouver,Vancouver,British Columbia
1190,government,Department of State,undefined,10398.33,Other,Trump Golf Club Doonberg,NaN,Trump International Golf Links and Hotel Ireland,Doonberg,Ireland
1191,government,Department of State,undefined,592.13,Other,Trump Golf Club Doonberg,NaN,Trump International Golf Links and Hotel Ireland,Doonberg,Ireland
1192,government,Department of Defense,"Jan 24, 2017",103.25,Other,Trump Hotel Honolulu,Financial Institution,Trump International Hotel Waikiki,Honolulu,HI

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1193 entries, 0 to 1192
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   type               1193 non-null   object
 1   source             1193 non-null   object
 2   date               1193 non-null   object
 3   amount             1193 non-null   float64
 4   purpose_scrubbed   1193 non-null   object
 5   property_scrubbed  1193 non-null   object
 6   purpose            1182 non-null   object
 7   property           1193 non-null   object
 8   city               1160 non-null   object
 9   state              1158 non-null   object
dtypes: float64(1), object(9)
memory usage: 93.3+ KB